# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Random
      include RandomBytes
      include RandomId
      include RandomInteger
      include RandomPassword
      include RandomPet
      include RandomShuffle
      include RandomString
      include RandomUuid
      include RandomUuid4
      include RandomUuid7
    end
  end
end
