# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_pet/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomPet
    include Pangea::Resources::ResourceBuilder

    define_resource :random_pet,
      attributes_class: Random::Types::PetAttributes,
      outputs: { id: :id },
      map_present: [:keepers, :prefix]
  end
  module Random
    include RandomPet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
