# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Random::Types
  include Dry.Types()

  class PetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Random::Types

    attribute? :keepers, T::Hash.optional
    attribute? :prefix, T::String.optional
  end
end
