# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_shuffle/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomShuffle
    include Pangea::Resources::ResourceBuilder

    define_resource :random_shuffle,
      attributes_class: Random::Types::ShuffleAttributes,
      outputs: { id: :id },
      map: [:input],
      map_present: [:keepers, :result_count, :seed]
  end
  module Random
    include RandomShuffle
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
