# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_id/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomId
    include Pangea::Resources::ResourceBuilder

    define_resource :random_id,
      attributes_class: Random::Types::IdAttributes,
      outputs: { id: :id },
      map: [:byte_length],
      map_present: [:keepers, :prefix]
  end
  module Random
    include RandomId
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
