# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

# Random resources
require_relative 'pangea/resources/random_bytes/resource'
require_relative 'pangea/resources/random_id/resource'
require_relative 'pangea/resources/random_integer/resource'
require_relative 'pangea/resources/random_password/resource'
require_relative 'pangea/resources/random_pet/resource'
require_relative 'pangea/resources/random_shuffle/resource'
require_relative 'pangea/resources/random_string/resource'
require_relative 'pangea/resources/random_uuid/resource'
require_relative 'pangea/resources/random_uuid4/resource'
require_relative 'pangea/resources/random_uuid7/resource'

# Random module aggregator
require_relative 'pangea/resources/random'
