# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_integer/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomInteger
    include Pangea::Resources::ResourceBuilder

    define_resource :random_integer,
      attributes_class: Random::Types::IntegerAttributes,
      outputs: { id: :id },
      map: [:max, :min],
      map_present: [:keepers, :seed]
  end
  module Random
    include RandomInteger
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
