# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_uuid4/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomUuid4
    include Pangea::Resources::ResourceBuilder

    define_resource :random_uuid4,
      attributes_class: Random::Types::Uuid4Attributes,
      outputs: { id: :id },
      map_present: [:keepers]
  end
  module Random
    include RandomUuid4
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
