# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Random::Types
  include Dry.Types()

  class Uuid4Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Random::Types

    attribute? :keepers, T::Hash.optional
  end
end
