# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_bytes/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomBytes
    include Pangea::Resources::ResourceBuilder

    define_resource :random_bytes,
      attributes_class: Random::Types::BytesAttributes,
      outputs: { id: :id },
      map: [:length],
      map_present: [:keepers]
  end
  module Random
    include RandomBytes
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
