# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/random_password/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module RandomPassword
    include Pangea::Resources::ResourceBuilder

    define_resource :random_password,
      attributes_class: Random::Types::PasswordAttributes,
      outputs: { id: :id },
      map: [:length],
      map_present: [:keepers, :override_special]
  end
  module Random
    include RandomPassword
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Random)
