# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a random_id resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::RandomId do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { byte_length: 3.14 } }

  describe ':random_id' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'random_id', 'test')
        validate_required_attributes(config, [:byte_length])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_id('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:random_id)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_id('test', required_attrs)

        expect(ref.id).to eq("${random_id.test.id}")
        expect(ref.b64_std).to eq("${random_id.test.b64_std}")
        expect(ref.b64_url).to eq("${random_id.test.b64_url}")
        expect(ref.dec).to eq("${random_id.test.dec}")
        expect(ref.hex).to eq("${random_id.test.hex}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_id', 'test')
        expect(config).not_to have_key('b64_std')
        expect(config).not_to have_key('b64_url')
        expect(config).not_to have_key('dec')
        expect(config).not_to have_key('hex')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ keepers: { 'key1' => 'val1' }, prefix: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_id', 'full')
        expect(config).to have_key('keepers')
        expect(config).to have_key('prefix')
      end
    end

    context 'optional attributes' do
      it 'includes keepers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('opt', required_attrs.merge(keepers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_id', 'opt')
        expect(config).to have_key('keepers')
      end

      it 'omits keepers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_id', 'minimal')
        expect(config).not_to have_key('keepers')
      end
      it 'includes prefix when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('opt', required_attrs.merge(prefix: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_id', 'opt')
        expect(config).to have_key('prefix')
      end

      it 'omits prefix when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_id', 'minimal')
        expect(config).not_to have_key('prefix')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_id', 'typed')
        expect(config['byte_length']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_id('first', required_attrs)
        synth.random_id('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'random_id')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :random_id,
    method: :random_id,
    required_attrs: { byte_length: 3.14 },
    expected_outputs: [:id, :b64_std, :b64_url, :dec, :hex],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
