# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a random_bytes resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::RandomBytes do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { length: 3.14 } }

  describe ':random_bytes' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'random_bytes', 'test')
        validate_required_attributes(config, [:length])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_bytes('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:random_bytes)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_bytes('test', required_attrs)

        expect(ref.id).to eq("${random_bytes.test.id}")
        expect(ref.base64).to eq("${random_bytes.test.base64}")
        expect(ref.hex).to eq("${random_bytes.test.hex}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_bytes', 'test')
        expect(config).not_to have_key('base64')
        expect(config).not_to have_key('hex')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ keepers: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_bytes', 'full')
        expect(config).to have_key('keepers')
      end
    end

    context 'optional attributes' do
      it 'includes keepers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('opt', required_attrs.merge(keepers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_bytes', 'opt')
        expect(config).to have_key('keepers')
      end

      it 'omits keepers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_bytes', 'minimal')
        expect(config).not_to have_key('keepers')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:base64, :hex]
        expect(sensitive_fields).to include(:base64)
        expect(sensitive_fields).to include(:hex)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_bytes', 'typed')
        expect(config['length']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_bytes('first', required_attrs)
        synth.random_bytes('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'random_bytes')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :random_bytes,
    method: :random_bytes,
    required_attrs: { length: 3.14 },
    expected_outputs: [:id, :base64, :hex],
    sensitive_fields: [:base64, :hex],
    immutable_fields: [],
    boolean_fields: []
end
