# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a random_uuid4 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::RandomUuid4 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':random_uuid4' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'random_uuid4', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_uuid4('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:random_uuid4)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_uuid4('test', required_attrs)

        expect(ref.id).to eq("${random_uuid4.test.id}")
        expect(ref.result).to eq("${random_uuid4.test.result}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_uuid4', 'test')
        expect(config).not_to have_key('result')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ keepers: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_uuid4', 'full')
        expect(config).to have_key('keepers')
      end
    end

    context 'optional attributes' do
      it 'includes keepers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('opt', required_attrs.merge(keepers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_uuid4', 'opt')
        expect(config).to have_key('keepers')
      end

      it 'omits keepers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_uuid4', 'minimal')
        expect(config).not_to have_key('keepers')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_uuid4', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_uuid4('first', required_attrs)
        synth.random_uuid4('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'random_uuid4')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :random_uuid4,
    method: :random_uuid4,
    required_attrs: {},
    expected_outputs: [:id, :result],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
