# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a random_password resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::RandomPassword do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { length: 3.14 } }

  describe ':random_password' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'random_password', 'test')
        validate_required_attributes(config, [:length])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_password('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:random_password)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_password('test', required_attrs)

        expect(ref.id).to eq("${random_password.test.id}")
        expect(ref.bcrypt_hash).to eq("${random_password.test.bcrypt_hash}")
        expect(ref.lower).to eq("${random_password.test.lower}")
        expect(ref.min_lower).to eq("${random_password.test.min_lower}")
        expect(ref.min_numeric).to eq("${random_password.test.min_numeric}")
        expect(ref.min_special).to eq("${random_password.test.min_special}")
        expect(ref.min_upper).to eq("${random_password.test.min_upper}")
        expect(ref.number).to eq("${random_password.test.number}")
        expect(ref.numeric).to eq("${random_password.test.numeric}")
        expect(ref.result).to eq("${random_password.test.result}")
        expect(ref.special).to eq("${random_password.test.special}")
        expect(ref.upper).to eq("${random_password.test.upper}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_password', 'test')
        expect(config).not_to have_key('bcrypt_hash')
        expect(config).not_to have_key('lower')
        expect(config).not_to have_key('min_lower')
        expect(config).not_to have_key('min_numeric')
        expect(config).not_to have_key('min_special')
        expect(config).not_to have_key('min_upper')
        expect(config).not_to have_key('number')
        expect(config).not_to have_key('numeric')
        expect(config).not_to have_key('result')
        expect(config).not_to have_key('special')
        expect(config).not_to have_key('upper')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ keepers: { 'key1' => 'val1' }, override_special: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_password', 'full')
        expect(config).to have_key('keepers')
        expect(config).to have_key('override_special')
      end
    end

    context 'optional attributes' do
      it 'includes keepers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('opt', required_attrs.merge(keepers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_password', 'opt')
        expect(config).to have_key('keepers')
      end

      it 'omits keepers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_password', 'minimal')
        expect(config).not_to have_key('keepers')
      end
      it 'includes override_special when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('opt', required_attrs.merge(override_special: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_password', 'opt')
        expect(config).to have_key('override_special')
      end

      it 'omits override_special when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_password', 'minimal')
        expect(config).not_to have_key('override_special')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:bcrypt_hash, :result]
        expect(sensitive_fields).to include(:bcrypt_hash)
        expect(sensitive_fields).to include(:result)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_password', 'typed')
        expect(config['length']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_password('first', required_attrs)
        synth.random_password('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'random_password')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :random_password,
    method: :random_password,
    required_attrs: { length: 3.14 },
    expected_outputs: [:id, :bcrypt_hash, :lower, :min_lower, :min_numeric, :min_special, :min_upper, :number, :numeric, :result, :special, :upper],
    sensitive_fields: [:bcrypt_hash, :result],
    immutable_fields: [],
    boolean_fields: []
end
