# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a random_shuffle resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::RandomShuffle do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { input: ['test-value'] } }

  describe ':random_shuffle' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'random_shuffle', 'test')
        validate_required_attributes(config, [:input])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_shuffle('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:random_shuffle)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.random_shuffle('test', required_attrs)

        expect(ref.id).to eq("${random_shuffle.test.id}")
        expect(ref.result).to eq("${random_shuffle.test.result}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_shuffle', 'test')
        expect(config).not_to have_key('result')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ keepers: { 'key1' => 'val1' }, result_count: 3.14, seed: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_shuffle', 'full')
        expect(config).to have_key('keepers')
        expect(config).to have_key('result_count')
        expect(config).to have_key('seed')
      end
    end

    context 'optional attributes' do
      it 'includes keepers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('opt', required_attrs.merge(keepers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_shuffle', 'opt')
        expect(config).to have_key('keepers')
      end

      it 'omits keepers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_shuffle', 'minimal')
        expect(config).not_to have_key('keepers')
      end
      it 'includes result_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('opt', required_attrs.merge(result_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_shuffle', 'opt')
        expect(config).to have_key('result_count')
      end

      it 'omits result_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_shuffle', 'minimal')
        expect(config).not_to have_key('result_count')
      end
      it 'includes seed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('opt', required_attrs.merge(seed: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_shuffle', 'opt')
        expect(config).to have_key('seed')
      end

      it 'omits seed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'random_shuffle', 'minimal')
        expect(config).not_to have_key('seed')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'random_shuffle', 'typed')
        expect(config['input']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.random_shuffle('first', required_attrs)
        synth.random_shuffle('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'random_shuffle')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :random_shuffle,
    method: :random_shuffle,
    required_attrs: { input: ['test-value'] },
    expected_outputs: [:id, :result],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
